# Generated by Django 4.0.3 on 2022-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default=None, upload_to='image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
