# Generated by Django 4.0.3 on 2022-05-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='photo',
            new_name='image',
        ),
    ]
