# Generated by Django 4.0.3 on 2022-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_rename_photo_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тэг'),
        ),
    ]
