# Generated by Django 4.0.3 on 2022-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_remove_blog_comment_remove_comment_id_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
